### ISSUE TITLE
Incompatibility with gitlab gem v4.6.0

### ISSUE THREAD

**Issue by notsatyarth** [danger/danger-gitlab-gem#6]
Hi,

There seems to compatibility issues with [v4.6.0](https://github.com/NARKOZ/gitlab/releases/tag/v4.6.0) of the gitlab gem. The relevant stacktrace is
```
/usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gitlab-4.6.0/lib/gitlab/client/commits.rb:5:in `<top (required)>': Commits is not a module (TypeError)
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gitlab-4.6.0/lib/gitlab/client.rb:6:in `block in <class:Client>'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gitlab-4.6.0/lib/gitlab/client.rb:6:in `each'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gitlab-4.6.0/lib/gitlab/client.rb:6:in `<class:Client>'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gitlab-4.6.0/lib/gitlab/client.rb:5:in `<module:Gitlab>'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gitlab-4.6.0/lib/gitlab/client.rb:3:in `<top (required)>'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gitlab-4.6.0/lib/gitlab.rb:12:in `<top (required)>'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.7.0/lib/danger/request_sources/gitlab.rb:34:in `client'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.7.0/lib/danger/ci_source/gitlab_ci.rb:40:in `determine_merge_request_id'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.7.0/lib/danger/ci_source/gitlab_ci.rb:31:in `validates_as_pr?'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.7.0/lib/danger/danger_core/environment_manager.rb:15:in `pr?'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.7.0/lib/danger/danger_core/executor.rb:62:in `validate_pr!'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.7.0/lib/danger/danger_core/executor.rb:46:in `validate!'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.7.0/lib/danger/danger_core/executor.rb:21:in `run'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.7.0/lib/danger/commands/runner.rb:70:in `run'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /usr/local/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.7.0/bin/danger:5:in `<top (required)>'
	from /usr/local/rbenv/versions/2.3.1/bin/danger:23:in `load'
	from /usr/local/rbenv/versions/2.3.1/bin/danger:23:in `<main>'
```

I think it would make sense specify a gitlab gem version for now while this is fixed.

**Comment by orta** [comment]
I wonder if this is just a gitlab gem issue, we're only importing the gem at [line 34](https://github.com/danger/danger/blob/master/lib/danger/request_sources/gitlab.rb#L34) which triggers the crash

I'd recommend using the Gemfile to lock to an earlier version, I expect they'll fix this in a new release

**Comment by notsatyarth** [comment]
Yes I've done the same. However since the purpose of the the `danger-gitlab` gem is to ensure compatibility. Dont you think the gemspec here should cater to this too?

**Comment by orta** [comment]
Personally, I'd rather not lock the version - if a bunch of people start reporting this crash then I'm fine to do so, but GitLab changes pretty often and locking the version means that starts to go out of sync
