### ISSUE TITLE
NoMethodError: undefined method `description' for #<Gitlab::ObjectifiedHash:0x00007f92a3261258>

### ISSUE THREAD

**Issue by praveenmukilan** [danger/danger-gitlab-gem#7]
Hi @orta , 

Kindly help as I am stuck at this issue. Getting NoMethodError. I have also tried individual gem versions of danger (5.5.13, 5.9.0, 5.7.1) & gitlab (4.6.1, 4.7.0). Facing different exceptions with them.

Gitlab gem 4.7.0 from irb works fine. The last working danger & gitlab integration version for me was on danger-5.3.4 & gitlab 4.2.0 on gitlab api v3 for gitlab v10.x

Recently we did an upgrade on gitlab and things are broken then on.

**Env**
gitlab EE v11.5
danger-gitlab - danger 5.9.0 & gitlab 4.7.0
gitlab api v4
required env variables : DANGER_GITLAB_API_TOKEN, DANGER_GITLAB_HOST, DANGER_GITLAB_API_BASE_URL are all set.

StackTrace :

```
NoMethodError: undefined method `description' for #<Gitlab::ObjectifiedHash:0x00007f92a3261258>
  /Users/user/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/gitlab-4.7.0/lib/gitlab/objectified_hash.rb:28:in `method_missing'
  /Users/user/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/danger-5.9.0/lib/danger/request_sources/gitlab.rb:109:in `ignored_violations_from_pr'
  /Users/user/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/danger-5.9.0/lib/danger/request_sources/gitlab.rb:105:in `fetch_details'
  /Users/user/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/danger-5.9.0/lib/danger/danger_core/environment_manager.rb:51:in `fill_environment_vars'
  /Users/user/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/danger-5.9.0/lib/danger/danger_core/dangerfile.rb:266:in `run'
  /Users/user/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/danger-5.9.0/lib/danger/danger_core/executor.rb:28:in `run'
  /Users/user/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/danger-5.9.0/lib/danger/commands/runner.rb:70:in `run'
  /Users/user/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /Users/user/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/danger-5.9.0/bin/danger:5:in `<top (required)>'
  /Users/user/.rbenv/versions/2.4.2/bin/danger:23:in `load'
  /Users/user/.rbenv/versions/2.4.2/bin/danger:23:in `<top (required)>'
Build step 'Execute Scripts' changed build result to UNSTABLE
```

**Comment by orta** [comment]
Sorry, I don't use GitLab, so I don't have too much insight - I'd follow the stack trace from `ignored_violations_from_pr` and see what looks suspicious

**Comment by praveenmukilan** [comment]
noted thanks @orta
